import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import {QueryProvider} from "@/providers/query-provider";
import {SheetProvider} from "@/providers/sheet-provider";
import {Toaster} from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
        <html lang="en">
        <body className={inter.className}>
        <QueryProvider>
            {/*sheet provider is used to render the new account sheet*/}
            <SheetProvider />
            {/*the query provider has 'use client but since passed as children there is no problem'*/}
            <Toaster position='top-center' richColors />
            {children}
        </QueryProvider>
        </body>
        </html>
      </ClerkProvider>

  );
}
